### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by opcodewriter** [vinsonchuong/phantomjs-adapter#1]
First of all, the package doesn't seem it's been published:
https://www.npmjs.com/package/phantomjs-promise-es6

Second, can you please help with a small write-up how to install your library and the dependencies?
I assume I need Babel with ES7 support. 

Thank you

**Comment by vinsonchuong** [comment]
Hello, thanks a lot for your interest in my library! It's still a work in progress; so, that's why it hasn't been published yet. I'll be working on this more in the coming weeks. When it's ready for use, I'll add detailed usage instructions to the readme and update this issue.

Thanks!

**Comment by vinsonchuong** [comment]
@opcodewriter, I renamed the tool to `phantomjs-adapter` and have since published it.

This tool hasn't seen very much usage; so, I don't know what failure conditions haven't been covered yet.

I am working on this adapter at a steady pace and am using it to test some of my other projects. But, I haven't had the chance to use it to power end-to-end testing on a web frontend.
